# Generated by Django 3.1.1 on 2020-10-06 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20201006_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='resim.png', null=True, upload_to=''),
        ),
    ]
