# Generated by Django 3.1.1 on 2020-10-11 15:05

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_bilgilendirme_reports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bilgilendirme',
            name='yazi',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='yazi'),
        ),
    ]
