# Generated by Django 3.1.1 on 2020-10-14 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_auto_20201011_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
