# Generated by Django 3.1.1 on 2020-10-17 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_reports_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='read',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='email_host',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='email_host_password',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='email_host_user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='email_port',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
