# Generated by Django 3.1.1 on 2020-10-18 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_reports_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='gönderme tarihi'),
        ),
    ]
